stellaris:
  executable: C:/SteamHome/steamapps/common/Stellaris/Stellaris.exe
  root: # will become parent directory of executable
  imageMagickConvert: C:/ImageMagick710Q16HDRI-x64/convert
  documents: #All paths below will be loaded as full paths automatically
    root: Documents/Paradox Interactive/Stellaris
    db: launcher-v2.sqlite
    logs: logs
    mods: mods
    crashes: crashes
  index:
    root: C:/StellarisIndex
    images: C:/StellarisImages
    stellaris: C:/StellarisIndex/000_Stellaris
    mod: C:/StellarisIndex/001_ActivePlayset
    all: C:/StellarisIndex/002_AllMods
    merge: C:/Users/bexac/Documents/Paradox Interactive/Stellaris/mod/BCG-BuildRoot
    cleanMerge: true
    build: true
    mod_crunch: C:/StellarisIndex/004_ModCrunch
    links: C:/StellarisIndex/005_Links
  imageMagickHome: C:/ImageMagick710Q16HDRI-x64
  descriptor: C:/Users/bexac/Desktop/Code/starkeeper-mod-crunch/descriptor.mod

